name: Auto Merge Translation Branch

on:
  push:
    branches:
      - "Carol-6block-patch-*"

permissions:
  contents: write

jobs:
  merge-to-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: |
          git fetch origin

      - name: Merge current branch into main
        run: |
          BRANCH="${GITHUB_REF_NAME}"

          echo "Current branch: $BRANCH"

          git checkout main

          git pull origin main

          git merge origin/$BRANCH --no-edit

          git push origin main

      - name: Delete merged branch
        run: |
          git push origin --delete "${GITHUB_REF_NAME}"
